// default package
// Generated 15 juin 2011 16:02:56 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alarmes generated by hbm2java
 */
@Entity
@Table(name = "alarmes", catalog = "corepharma")
public class Alarmes implements java.io.Serializable {

	private Integer idAlarme;
	private String typeAlarme;
	private String dateCreation;
	private String dateModification;
	private String nombreDemande;

	public Alarmes() {
	}

	public Alarmes(String typeAlarme, String dateCreation,
			String dateModification, String nombreDemande) {
		this.typeAlarme = typeAlarme;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.nombreDemande = nombreDemande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAlarme", unique = true, nullable = false)
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "typeAlarme", length = 254)
	public String getTypeAlarme() {
		return this.typeAlarme;
	}

	public void setTypeAlarme(String typeAlarme) {
		this.typeAlarme = typeAlarme;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "nombreDemande", length = 254)
	public String getNombreDemande() {
		return this.nombreDemande;
	}

	public void setNombreDemande(String nombreDemande) {
		this.nombreDemande = nombreDemande;
	}

}
