// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "clients", catalog = "corepharma")
public class Clients implements java.io.Serializable {

	private Integer idClient;
	private String nom;
	private String prenom;
	private Boolean etatClient;
	private String tel;
	private String email;
	private Integer idNumeroCompte;
	private String numeroIdentification;
	private String typeClient;
	private String dateCreation;
	private String dateModification;
	private String auteurCreation;
	private String auteurModification;

	public Clients() {
	}

	public Clients(String nom, String prenom, Boolean etatClient, String tel,
			String email, Integer idNumeroCompte, String numeroIdentification,
			String typeClient, String dateCreation, String dateModification,
			String auteurCreation, String auteurModification) {
		this.nom = nom;
		this.prenom = prenom;
		this.etatClient = etatClient;
		this.tel = tel;
		this.email = email;
		this.idNumeroCompte = idNumeroCompte;
		this.numeroIdentification = numeroIdentification;
		this.typeClient = typeClient;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idClient", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "etatClient")
	public Boolean getEtatClient() {
		return this.etatClient;
	}

	public void setEtatClient(Boolean etatClient) {
		this.etatClient = etatClient;
	}

	@Column(name = "tel", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "idNumeroCompte")
	public Integer getIdNumeroCompte() {
		return this.idNumeroCompte;
	}

	public void setIdNumeroCompte(Integer idNumeroCompte) {
		this.idNumeroCompte = idNumeroCompte;
	}

	@Column(name = "numeroIdentification", length = 254)
	public String getNumeroIdentification() {
		return this.numeroIdentification;
	}

	public void setNumeroIdentification(String numeroIdentification) {
		this.numeroIdentification = numeroIdentification;
	}

	@Column(name = "typeClient", length = 254)
	public String getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(String typeClient) {
		this.typeClient = typeClient;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "auteurCreation", length = 254)
	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	@Column(name = "auteurModification", length = 254)
	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

}
