// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commandesproduits generated by hbm2java
 */
@Entity
@Table(name = "commandesproduits", catalog = "corepharma")
public class Commandesproduits implements java.io.Serializable {

	private Integer idCommandesProduits;
	private Integer idProduit;
	private Integer idCommande;

	public Commandesproduits() {
	}

	public Commandesproduits(Integer idProduit, Integer idCommande) {
		this.idProduit = idProduit;
		this.idCommande = idCommande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommandesProduits", unique = true, nullable = false)
	public Integer getIdCommandesProduits() {
		return this.idCommandesProduits;
	}

	public void setIdCommandesProduits(Integer idCommandesProduits) {
		this.idCommandesProduits = idCommandesProduits;
	}

	@Column(name = "idProduit")
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idCommande")
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

}
