// default package
// Generated 15 juin 2011 16:02:56 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commandes generated by hbm2java
 */
@Entity
@Table(name = "commandes", catalog = "corepharma")
public class Commandes implements java.io.Serializable {

	private Integer idCommande;
	private Integer idClient;
	private Integer idFournisseur;
	private Integer idAlarme;
	private String auteurModification;
	private String numeroCommande;
	private String fournisseurCommande;
	private String etatCommande;
	private Double acompte;
	private Double soldeRestant;
	private String dateLivraisonSouhaite;
	private String dateLivraisonEffective;
	private String responsableCommande;
	private String dateCreation;
	private String dateModification;
	private String auteurCreation;

	public Commandes() {
	}

	public Commandes(Integer idClient, Integer idFournisseur, Integer idAlarme,
			String auteurModification, String numeroCommande,
			String fournisseurCommande, String etatCommande, Double acompte,
			Double soldeRestant, String dateLivraisonSouhaite,
			String dateLivraisonEffective, String responsableCommande,
			String dateCreation, String dateModification, String auteurCreation) {
		this.idClient = idClient;
		this.idFournisseur = idFournisseur;
		this.idAlarme = idAlarme;
		this.auteurModification = auteurModification;
		this.numeroCommande = numeroCommande;
		this.fournisseurCommande = fournisseurCommande;
		this.etatCommande = etatCommande;
		this.acompte = acompte;
		this.soldeRestant = soldeRestant;
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
		this.dateLivraisonEffective = dateLivraisonEffective;
		this.responsableCommande = responsableCommande;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@Column(name = "idClient")
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "auteurModification", length = 254)
	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	@Column(name = "numeroCommande", length = 254)
	public String getNumeroCommande() {
		return this.numeroCommande;
	}

	public void setNumeroCommande(String numeroCommande) {
		this.numeroCommande = numeroCommande;
	}

	@Column(name = "fournisseurCommande", length = 254)
	public String getFournisseurCommande() {
		return this.fournisseurCommande;
	}

	public void setFournisseurCommande(String fournisseurCommande) {
		this.fournisseurCommande = fournisseurCommande;
	}

	@Column(name = "etatCommande", length = 254)
	public String getEtatCommande() {
		return this.etatCommande;
	}

	public void setEtatCommande(String etatCommande) {
		this.etatCommande = etatCommande;
	}

	@Column(name = "acompte", precision = 22, scale = 0)
	public Double getAcompte() {
		return this.acompte;
	}

	public void setAcompte(Double acompte) {
		this.acompte = acompte;
	}

	@Column(name = "soldeRestant", precision = 22, scale = 0)
	public Double getSoldeRestant() {
		return this.soldeRestant;
	}

	public void setSoldeRestant(Double soldeRestant) {
		this.soldeRestant = soldeRestant;
	}

	@Column(name = "dateLivraisonSouhaite", length = 254)
	public String getDateLivraisonSouhaite() {
		return this.dateLivraisonSouhaite;
	}

	public void setDateLivraisonSouhaite(String dateLivraisonSouhaite) {
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
	}

	@Column(name = "dateLivraisonEffective", length = 254)
	public String getDateLivraisonEffective() {
		return this.dateLivraisonEffective;
	}

	public void setDateLivraisonEffective(String dateLivraisonEffective) {
		this.dateLivraisonEffective = dateLivraisonEffective;
	}

	@Column(name = "responsableCommande", length = 254)
	public String getResponsableCommande() {
		return this.responsableCommande;
	}

	public void setResponsableCommande(String responsableCommande) {
		this.responsableCommande = responsableCommande;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "auteurCreation", length = 254)
	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

}
