// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comptesbancaires generated by hbm2java
 */
@Entity
@Table(name = "comptesbancaires", catalog = "corepharma")
public class Comptesbancaires implements java.io.Serializable {

	private Integer idCompte;
	private String codeBanque;
	private String codeGuichet;
	private String numeroCompte;
	private String rib;
	private String iban;
	private String bicAdresseSwift;

	public Comptesbancaires() {
	}

	public Comptesbancaires(String codeBanque, String codeGuichet,
			String numeroCompte, String rib, String iban, String bicAdresseSwift) {
		this.codeBanque = codeBanque;
		this.codeGuichet = codeGuichet;
		this.numeroCompte = numeroCompte;
		this.rib = rib;
		this.iban = iban;
		this.bicAdresseSwift = bicAdresseSwift;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCompte", unique = true, nullable = false)
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@Column(name = "codeBanque", length = 254)
	public String getCodeBanque() {
		return this.codeBanque;
	}

	public void setCodeBanque(String codeBanque) {
		this.codeBanque = codeBanque;
	}

	@Column(name = "codeGuichet", length = 254)
	public String getCodeGuichet() {
		return this.codeGuichet;
	}

	public void setCodeGuichet(String codeGuichet) {
		this.codeGuichet = codeGuichet;
	}

	@Column(name = "numeroCompte", length = 254)
	public String getNumeroCompte() {
		return this.numeroCompte;
	}

	public void setNumeroCompte(String numeroCompte) {
		this.numeroCompte = numeroCompte;
	}

	@Column(name = "rib", length = 254)
	public String getRib() {
		return this.rib;
	}

	public void setRib(String rib) {
		this.rib = rib;
	}

	@Column(name = "iban", length = 254)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "bicAdresseSwift", length = 254)
	public String getBicAdresseSwift() {
		return this.bicAdresseSwift;
	}

	public void setBicAdresseSwift(String bicAdresseSwift) {
		this.bicAdresseSwift = bicAdresseSwift;
	}

}
