// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fournisseurs generated by hbm2java
 */
@Entity
@Table(name = "fournisseurs", catalog = "corepharma")
public class Fournisseurs implements java.io.Serializable {

	private Integer idFournisseur;
	private Integer idCompte;
	private Integer idAlarme;
	private String nomFournisseur;
	private String codeFournisseur;
	private Integer idNumeroCompte;
	private String tel;
	private String adresse;
	private String jourLivraison;
	private Boolean etatFournisseur;
	private String dateCreation;
	private String dateModification;
	private String auteurCreation;
	private String auteurModification;

	public Fournisseurs() {
	}

	public Fournisseurs(Integer idCompte, Integer idAlarme,
			String nomFournisseur, String codeFournisseur,
			Integer idNumeroCompte, String tel, String adresse,
			String jourLivraison, Boolean etatFournisseur, String dateCreation,
			String dateModification, String auteurCreation,
			String auteurModification) {
		this.idCompte = idCompte;
		this.idAlarme = idAlarme;
		this.nomFournisseur = nomFournisseur;
		this.codeFournisseur = codeFournisseur;
		this.idNumeroCompte = idNumeroCompte;
		this.tel = tel;
		this.adresse = adresse;
		this.jourLivraison = jourLivraison;
		this.etatFournisseur = etatFournisseur;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFournisseur", unique = true, nullable = false)
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idCompte")
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "nomFournisseur", length = 254)
	public String getNomFournisseur() {
		return this.nomFournisseur;
	}

	public void setNomFournisseur(String nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}

	@Column(name = "codeFournisseur", length = 254)
	public String getCodeFournisseur() {
		return this.codeFournisseur;
	}

	public void setCodeFournisseur(String codeFournisseur) {
		this.codeFournisseur = codeFournisseur;
	}

	@Column(name = "idNumeroCompte")
	public Integer getIdNumeroCompte() {
		return this.idNumeroCompte;
	}

	public void setIdNumeroCompte(Integer idNumeroCompte) {
		this.idNumeroCompte = idNumeroCompte;
	}

	@Column(name = "tel", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "jourLivraison", length = 254)
	public String getJourLivraison() {
		return this.jourLivraison;
	}

	public void setJourLivraison(String jourLivraison) {
		this.jourLivraison = jourLivraison;
	}

	@Column(name = "etatFournisseur")
	public Boolean getEtatFournisseur() {
		return this.etatFournisseur;
	}

	public void setEtatFournisseur(Boolean etatFournisseur) {
		this.etatFournisseur = etatFournisseur;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "auteurCreation", length = 254)
	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	@Column(name = "auteurModification", length = 254)
	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

}
