// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pharmacies generated by hbm2java
 */
@Entity
@Table(name = "pharmacies", catalog = "corepharma")
public class Pharmacies implements java.io.Serializable {

	private Integer idPharmacie;
	private String nomPharmacie;
	private String codePharmacie;
	private String numeroLicence;
	private Integer nomProprietaire;
	private Integer etatPharmacie;

	public Pharmacies() {
	}

	public Pharmacies(String nomPharmacie, String codePharmacie,
			String numeroLicence, Integer nomProprietaire, Integer etatPharmacie) {
		this.nomPharmacie = nomPharmacie;
		this.codePharmacie = codePharmacie;
		this.numeroLicence = numeroLicence;
		this.nomProprietaire = nomProprietaire;
		this.etatPharmacie = etatPharmacie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPharmacie", unique = true, nullable = false)
	public Integer getIdPharmacie() {
		return this.idPharmacie;
	}

	public void setIdPharmacie(Integer idPharmacie) {
		this.idPharmacie = idPharmacie;
	}

	@Column(name = "nomPharmacie", length = 254)
	public String getNomPharmacie() {
		return this.nomPharmacie;
	}

	public void setNomPharmacie(String nomPharmacie) {
		this.nomPharmacie = nomPharmacie;
	}

	@Column(name = "codePharmacie", length = 254)
	public String getCodePharmacie() {
		return this.codePharmacie;
	}

	public void setCodePharmacie(String codePharmacie) {
		this.codePharmacie = codePharmacie;
	}

	@Column(name = "numeroLicence", length = 254)
	public String getNumeroLicence() {
		return this.numeroLicence;
	}

	public void setNumeroLicence(String numeroLicence) {
		this.numeroLicence = numeroLicence;
	}

	@Column(name = "nomProprietaire")
	public Integer getNomProprietaire() {
		return this.nomProprietaire;
	}

	public void setNomProprietaire(Integer nomProprietaire) {
		this.nomProprietaire = nomProprietaire;
	}

	@Column(name = "etatPharmacie")
	public Integer getEtatPharmacie() {
		return this.etatPharmacie;
	}

	public void setEtatPharmacie(Integer etatPharmacie) {
		this.etatPharmacie = etatPharmacie;
	}

}
