// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "produits", catalog = "corepharma")
public class Produits implements java.io.Serializable {

	private Integer idProduit;
	private Integer idAlarme;
	private String nomProduit;
	private String codeProduit;
	private Integer prixProduit;
	private Integer quantiteActuel;
	private Integer quantiteAlarme;
	private String datePeremption;
	private String dateCreation;
	private String dateModification;
	private String auteurCreation;
	private String auteurModification;
	private String produitPanier;

	public Produits() {
	}

	public Produits(Integer idAlarme, String nomProduit, String codeProduit,
			Integer prixProduit, Integer quantiteActuel,
			Integer quantiteAlarme, String datePeremption, String dateCreation,
			String dateModification, String auteurCreation,
			String auteurModification) {
		this.idAlarme = idAlarme;
		this.nomProduit = nomProduit;
		this.codeProduit = codeProduit;
		this.prixProduit = prixProduit;
		this.quantiteActuel = quantiteActuel;
		this.quantiteAlarme = quantiteAlarme;
		this.datePeremption = datePeremption;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProduit", unique = true, nullable = false)
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "nomProduit", length = 254)
	public String getNomProduit() {
		return this.nomProduit;
	}

	public void setNomProduit(String nomProduit) {
		this.nomProduit = nomProduit;
	}

	@Column(name = "codeProduit", length = 254)
	public String getCodeProduit() {
		return this.codeProduit;
	}

	public void setCodeProduit(String codeProduit) {
		this.codeProduit = codeProduit;
	}

	@Column(name = "prixProduit", precision = 8, scale = 0)
	public Integer getPrixProduit() {
		return this.prixProduit;
	}

	public void setPrixProduit(Integer prixProduit) {
		this.prixProduit = prixProduit;
	}

	@Column(name = "quantiteActuel")
	public Integer getQuantiteActuel() {
		return this.quantiteActuel;
	}

	public void setQuantiteActuel(Integer quantiteActuel) {
		this.quantiteActuel = quantiteActuel;
	}

	@Column(name = "quantiteAlarme")
	public Integer getQuantiteAlarme() {
		return this.quantiteAlarme;
	}

	public void setQuantiteAlarme(Integer quantiteAlarme) {
		this.quantiteAlarme = quantiteAlarme;
	}

	@Column(name = "datePeremption", length = 254)
	public String getDatePeremption() {
		return this.datePeremption;
	}

	public void setDatePeremption(String datePeremption) {
		this.datePeremption = datePeremption;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "auteurCreation", length = 254)
	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	@Column(name = "auteurModification", length = 254)
	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	/**
	 * @return the produitPanier
	 */
	public String getProduitPanier() {
		return produitPanier;
	}

	/**
	 * @param produitPanier the produitPanier to set
	 */
	public void setProduitPanier(String produitPanier) {
		this.produitPanier = produitPanier;
	}

}
