// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Produitsfournisseurs generated by hbm2java
 */
@Entity
@Table(name = "produitsfournisseurs", catalog = "corepharma", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idProduit", "idFournisseur" }))
public class Produitsfournisseurs implements java.io.Serializable {

	private Integer idProduitsFournisseurs;
	private Integer idProduit;
	private Integer idFournisseur;

	public Produitsfournisseurs() {
	}

	public Produitsfournisseurs(Integer idProduit, Integer idFournisseur) {
		this.idProduit = idProduit;
		this.idFournisseur = idFournisseur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProduitsFournisseurs", unique = true, nullable = false)
	public Integer getIdProduitsFournisseurs() {
		return this.idProduitsFournisseurs;
	}

	public void setIdProduitsFournisseurs(Integer idProduitsFournisseurs) {
		this.idProduitsFournisseurs = idProduitsFournisseurs;
	}

	@Column(name = "idProduit")
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

}
