// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Venteproduit generated by hbm2java
 */
@Entity
@Table(name = "venteproduit", catalog = "corepharma")
public class Venteproduit implements java.io.Serializable {

	private Integer idVenteProduit;
	private Integer idVente;
	private Integer idProduit;

	public Venteproduit() {
	}

	public Venteproduit(Integer idVente, Integer idProduit) {
		this.idVente = idVente;
		this.idProduit = idProduit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVenteProduit", unique = true, nullable = false)
	public Integer getIdVenteProduit() {
		return this.idVenteProduit;
	}

	public void setIdVenteProduit(Integer idVenteProduit) {
		this.idVenteProduit = idVenteProduit;
	}

	@Column(name = "idVente")
	public Integer getIdVente() {
		return this.idVente;
	}

	public void setIdVente(Integer idVente) {
		this.idVente = idVente;
	}

	@Column(name = "idProduit")
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

}
