// default package
// Generated 27 avr. 2011 12:11:52 by Hibernate Tools 3.4.0.CR1
package corepharma.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ventes generated by hbm2java
 */
@Entity
@Table(name = "ventes", catalog = "corepharma")
public class Ventes implements java.io.Serializable {

	private Integer idVente;
	private Integer etatVente;
	private String dateCreation;
	private String dateModification;
	private String auteurCreation;
	private String auteurModification;
	private String codeVente;
	private Integer montantRecu;
	private Integer montantVente;

	public Ventes() {
	}

	public Ventes(Integer etatVente, String dateCreation,
			String dateModification, String auteurCreation,
			String auteurModification, String codeVente, Integer montantRecu,
			Integer montantVente) {
		this.etatVente = etatVente;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.auteurCreation = auteurCreation;
		this.auteurModification = auteurModification;
		this.codeVente = codeVente;
		this.montantRecu = montantRecu;
		this.montantVente = montantVente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVente", unique = true, nullable = false)
	public Integer getIdVente() {
		return this.idVente;
	}

	public void setIdVente(Integer idVente) {
		this.idVente = idVente;
	}

	@Column(name = "etatVente")
	public Integer getEtatVente() {
		return this.etatVente;
	}

	public void setEtatVente(Integer etatVente) {
		this.etatVente = etatVente;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "auteurCreation", length = 254)
	public String getAuteurCreation() {
		return this.auteurCreation;
	}

	public void setAuteurCreation(String auteurCreation) {
		this.auteurCreation = auteurCreation;
	}

	@Column(name = "auteurModification", length = 254)
	public String getAuteurModification() {
		return this.auteurModification;
	}

	public void setAuteurModification(String auteurModification) {
		this.auteurModification = auteurModification;
	}

	@Column(name = "codeVente", length = 254)
	public String getCodeVente() {
		return this.codeVente;
	}

	public void setCodeVente(String codeVente) {
		this.codeVente = codeVente;
	}

	@Column(name = "montantRecu", precision = 8, scale = 0)
	public Integer getMontantRecu() {
		return this.montantRecu;
	}

	public void setMontantRecu(Integer montantRecu) {
		this.montantRecu = montantRecu;
	}

	@Column(name = "montantVente", precision = 8, scale = 0)
	public Integer getMontantVente() {
		return this.montantVente;
	}

	public void setMontantVente(Integer montantVente) {
		this.montantVente = montantVente;
	}

}
